### ISSUE TITLE
as_namedtuple_iter with dataframes uses missing attribute

### ISSUE THREAD

**Issue by jackweitze** [terrierteam/ir_measures#30]
I might be misunderstanding the context of this:

https://github.com/terrierteam/ir_measures/blob/ddb2983387f0da877d821b3c32895bc0d71c8dc3/ir_measures/util.py#L113-L117

But it looks like `qrels.iteration` is only indexed when `iteration` is not in `self.qrels.columns`, resulting in an attribute error.

**Comment by seanmacavaney** [comment]
You're right- thanks! I'll fix ASAP, and add more comprehensive tests for the qrels converter.

**Comment by seanmacavaney** [comment]
The issue is now fixed, tests are in place & passing, and an updated version (0.2.3) is on pypi.
