### ISSUE TITLE
Accuracy metric

### ISSUE THREAD

**Issue by bpiwowar** [terrierteam/ir_measures#32]
I implemented in `experimaestro-ir` the accuracy metric (just to check that it was in line with the training accuracy). I could submit a pull request if you are interested; in that case, just tell me where it should be added (should I create an `AccuracyProvider`?)

**Comment by seanmacavaney** [comment]
Awesome, thanks! Is this pairwise accuracy among the qrels or something else?

I should add a guide for adding a new measure, but [this PR](https://github.com/terrierteam/ir_measures/pull/24) does a nice job showing what's needed. Basically:
 - A new measure definition (`Accuracy`?) with any measure parameters
 - A new provider definition (`AccuracyProvider`?) that provides an implementation for the measure
 - Tests for the new provider
 - A bit of boilerplate
