### ISSUE TITLE
Small typo in the "Reverse IR Measures" Demo

### ISSUE THREAD

**Issue by mam10eks** [terrierteam/ir_measures#39]
Dear all,

I just saw the very cool "Reverse IR Measures" demo located at [https://demo.ir-measur.es/reverse](https://demo.ir-measur.es/reverse).

There is a small typo on this page ("particualr" -> "particular").
(I could not find the code that renders the demo page, so I report the typo in this issue :))

Best Regards,

Maik

**Comment by seanmacavaney** [comment]
Thanks --- fixed. The demo pages are hosted in a different repo.

I hope you're finding the demos handy!
