### ISSUE TITLE
ir_measures.evaluator breaks when evaluating on multiple runs

### ISSUE THREAD

**Issue by grodino** [terrierteam/ir_measures#42]
Hi !

First of all, thanks a lot for this lib and the convenience it brings to IR evaluation.

I am using the `ir_measures.evaluator` to evaluate multiple runs with a single set of qrels. The evaluation of the first runs goes flawlessly but for all the subsequent evaluated runs, only one measure is reported, the rest are returned as 0. Here is a minimum example to reproduce the error:

```python3
import ir_measures
from ir_measures import alpha_nDCG, nDCG, P

sqrels = list(ir_measures.util.parse_trec_qrels("""
0 0 D0 0
0 0 D1 1
0 0 D2 1
0 1 D2 1
0 1 D3 2
0 0 D4 0
1 0 D0 1
1 0 D3 2
1 1 D5 2
"""))
qrels = list(ir_measures.util.parse_trec_qrels("""
0 0 D0 0
0 0 D1 1
0 1 D2 1
0 1 D3 1
0 0 D4 0
1 0 D0 1
1 0 D3 2
1 1 D5 2
"""))
run = list(ir_measures.util.parse_trec_run("""
0 0 D0 1 0.8 run
0 0 D2 2 0.7 run
0 0 D1 3 0.3 run
0 0 D3 4 0.4 run
0 0 D4 5 0.1 run
1 0 D1 1 0.8 run
1 0 D3 2 0.7 run
1 0 D4 3 0.3 run
1 0 D2 4 0.4 run
1 0 D10 4 8 run
"""))
measures = [nDCG@10, nDCG@100, nDCG@2, P@10]

evaluator = ir_measures.evaluator(
    measures,
    qrels,
)

# First time, the results are valid
print("\n".join(map(str, evaluator.iter_calc(run))))
print()

# Second time, the nDCG@2 and nDCG@100 are zero
print("\n".join(map(str, evaluator.iter_calc(run))))
```
In this example, it seems to affect only the nDCG when multiple cutoff values are used

Best,
Augustin

**Comment by seanmacavaney** [comment]
Thanks for reporting!

I'll look into this further and add test cases.

In the meantime, it looks like the problem doesn't happen when you re-create the evaluator object or call `ir_measures.iter_calc` directly.

**Comment by grodino** [comment]
> In the meantime, it looks like the problem doesn't happen when you re-create the evaluator object or call ir_measures.iter_calc directly.

In deed, this is what I ended up doing for now

**Comment by seanmacavaney** [comment]
Hey, quick update @grodino.

It looks like this is a bug from `pytrec_eval` itself:


```python
>>> import pytrec_eval
>>> qrel = {
>>>   '0': {'D0': 0, 'D1': 1, 'D2': 1, 'D3': 1, 'D4': 0},
>>>   '1': {'D0': 1, 'D3': 2, 'D5': 2}
>>> }
>>> run = {
>>>   '0': {'D0': 0.8, 'D2': 0.7, 'D1': 0.3, 'D3': 0.4, 'D4': 0.1},
>>>   '1': {'D1': 0.8, 'D3': 0.7, 'D4': 0.3, 'D2': 0.4, 'D10': 8.}
>>> }
>>> evaluator = pytrec_eval.RelevanceEvaluator(qrel, {'map', 'ndcg_cut.10,100,2'})
>>> print(evaluator.evaluate(run))
{'0': {'map': 0.6388888888888888, 'ndcg_cut_2': 0.38685280723454163, 'ndcg_cut_10': 0.7328286204777911, 'ndcg_cut_100': 0.7328286204777911}, '1': {'map': 0.1111111111111111, 'ndcg_cut_2': 0.0, 'ndcg_cut_10': 0.26582598262939583, 'ndcg_cut_100': 0.26582598262939583}}
>>> print(evaluator.evaluate(run))
{'0': {'map': 0.6388888888888888, 'ndcg_cut_10': 0.7328286204777911}, '1': {'map': 0.1111111111111111, 'ndcg_cut_10': 0.26582598262939583}}
# ^ second invocation is missing ndcg_cut_2, ndcg_cut_100
```

I wrote a bug report for it here: https://github.com/cvangysel/pytrec_eval/issues/38. Unfortunately, `pytrec_eval` is not really maintained anymore, but we have a fork of it [here](https://github.com/terrierteam/pytrec_eval) where we fix issues like this.

**Comment by cmacdonald** [comment]
Whats the cost of recreating pytrec_eval.RelevanceEvaluator() for each run?

**Comment by grodino** [comment]
> I wrote a bug report for it here: https://github.com/cvangysel/pytrec_eval/issues/38. Unfortunately, pytrec_eval is not really maintained anymore, but we have a fork of it [here](https://github.com/terrierteam/pytrec_eval) where we fix issues like this.

Ok, thank you for the heads up ! 

> Whats the cost of recreating pytrec_eval.RelevanceEvaluator() for each run?

It forces to recreate all the invokers which means converting (ie copying) the qrels and passing them to pytrec_eval. 
In practice it is not that big of a problem, I switched using `ir_measures.iter_calc` each time.

**Comment by seanmacavaney** [comment]
@grodino -- We've fixed the issue and pushed a new version of our pytrec_eval fork. If you install this version, it should solve your problem:

```bash
pip install pytrec-eval-terrier==0.5.4
```

**Comment by grodino** [comment]
Yup, it solves the issue, thanks a lot !
Closing the issue
