### ISSUE TITLE
avoid forking process for gdeval

### ISSUE THREAD

**Issue by seanmacavaney** [terrierteam/ir_measures#46]
This is overkill and shouldn't be necessary. Can cause problems when there's a large run loaded, and insufficient memory to copy it all.

**Comment by cmacdonald** [comment]
Not sure how this is possible while using the Python interpreter. All unix run new processes by forking followed by an exec, iirc. See also https://stackoverflow.com/a/49628198

**Comment by seanmacavaney** [comment]
Hmmm, alright.

For a bit more background, the problem came up when somebody tried to run ir_measures (a measure that wasn't even supported by gdeval), and it broke [here](https://github.com/terrierteam/ir_measures/blob/main/ir_measures/providers/gdeval_provider.py#L40) because it required too much memory to fork.

Maybe there's a way to at least detect if perl is available on the system without forking the process? Or reworking the `FallbackProvider` a bit such that it checks whether the provider supports the measure(s) before it checks whether the provider is available. Or, lowering the priority of gdeval.

**Comment by cmacdonald** [comment]
`shutil.which()` doesn't call an external program: 
https://github.com/python/cpython/blob/main/Lib/shutil.py#L1497

**Comment by cmacdonald** [comment]
Generally, `fork()` on unix uses copy-on-write, so overall memory usage is only increased when a memory page is written to. The exception seems to be when its a Java process, where lots of memory is required - see e.g. https://confluence.atlassian.com/bitbucketserverkb/forking-jvm-error-12-cannot-allocate-memory-or-error-12-not-enough-space-779171744.html

Use `shutil.which()` to detect Perl, sure, but I don't think the wider problem is easy to solve when there is a JVM around.
